USE [master]
GO

/****** Object:  Database [AndrewEdu]    Script Date: 05/23/2017 16:01:07 ******/
CREATE DATABASE [AndrewEdu] ON  PRIMARY 
( NAME = N'AndrewEdu', FILENAME = N'D:\SQL_Data\AndrewEdu.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AndrewEdu_log', FILENAME = N'D:\SQL_Data\AndrewEdu_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AndrewEdu] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AndrewEdu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AndrewEdu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AndrewEdu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AndrewEdu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AndrewEdu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AndrewEdu] SET ARITHABORT OFF 
GO

ALTER DATABASE [AndrewEdu] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AndrewEdu] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AndrewEdu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AndrewEdu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AndrewEdu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AndrewEdu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AndrewEdu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AndrewEdu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AndrewEdu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AndrewEdu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AndrewEdu] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AndrewEdu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AndrewEdu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AndrewEdu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AndrewEdu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AndrewEdu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AndrewEdu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AndrewEdu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AndrewEdu] SET  READ_WRITE 
GO

ALTER DATABASE [AndrewEdu] SET RECOVERY FULL 
GO

ALTER DATABASE [AndrewEdu] SET  MULTI_USER 
GO

ALTER DATABASE [AndrewEdu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AndrewEdu] SET DB_CHAINING OFF 
GO
USE [AndrewEdu]
GO

/****** Object:  Table [dbo].[Person]    Script Date: 05/23/2017 16:01:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Person](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nchar](100) NOT NULL,
	[ContactInformation_Id] [uniqueidentifier] NULL
) ON [PRIMARY]

GO


INSERT INTO Person(Id, Name, ContactInformation_Id)
VALUES (
	NEWID(),
	'Andrew Sinclair',
	NULL
), (
	NEWID(),
	'Jane Doe',
	NULL
)